name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'e2e/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/e2eTest.yml'

jobs:
  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    # Only run for PRs from the same repository (not forks)
    if: github.event.pull_request.head.repo.full_name == github.repository

    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.14.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Run E2E tests
        env:
          NOTION_API_KEY_E2E: ${{ secrets.NOTION_API_KEY_E2E }}
          NOTION_PARENT_PAGE_ID: ${{ secrets.NOTION_PARENT_PAGE_ID }}
          E2E_RATE_LIMIT_DELAY: '350'
          E2E_CLEANUP_ON_SUCCESS: 'true'
          E2E_VERBOSE_LOGGING: 'false'
        run: pnpm run test:e2e

  e2e-test-notification:
    name: Notify E2E Test Skipped
    runs-on: ubuntu-latest
    # Only run for PRs from forks
    if: github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `⚠️ **E2E Tests Skipped**

            E2E tests are not run for pull requests from forked repositories for security reasons.

            To run E2E tests locally:
            1. Copy \`e2e/.env.e2e.example\` to \`e2e/.env.e2e\`
            2. Add your Notion API credentials
            3. Run \`pnpm run test:e2e\` to execute the tests

            Maintainers will run E2E tests before merging.`;

            // Check if we already commented
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.data.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('E2E Tests Skipped')
            );

            if (!botComment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment,
              });
            }
